// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("EFCore.FSharp")>]
[<assembly: AssemblyProductAttribute("EFCore.FSharp")>]
[<assembly: AssemblyVersionAttribute("6.0.5")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-11-30T00:00:00.0000000+00:00")>]
[<assembly: AssemblyFileVersionAttribute("6.0.5")>]
[<assembly: AssemblyInformationalVersionAttribute("6.0.5")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","9b0e92f0fe99052d899a2c5bc55a5f8b61416127")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "EFCore.FSharp"
    let [<Literal>] AssemblyProduct = "EFCore.FSharp"
    let [<Literal>] AssemblyVersion = "6.0.5"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-11-30T00:00:00.0000000+00:00"
    let [<Literal>] AssemblyFileVersion = "6.0.5"
    let [<Literal>] AssemblyInformationalVersion = "6.0.5"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "9b0e92f0fe99052d899a2c5bc55a5f8b61416127"
