// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("EFCore.FSharp")>]
[<assembly: AssemblyProductAttribute("EFCore.FSharp")>]
[<assembly: AssemblyVersionAttribute("6.0.6")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2022-01-16T00:00:00.0000000+00:00")>]
[<assembly: AssemblyFileVersionAttribute("6.0.6")>]
[<assembly: AssemblyInformationalVersionAttribute("6.0.6")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","c142d04ac0b623f677933761209aacc8a16d337e")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "EFCore.FSharp"
    let [<Literal>] AssemblyProduct = "EFCore.FSharp"
    let [<Literal>] AssemblyVersion = "6.0.6"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2022-01-16T00:00:00.0000000+00:00"
    let [<Literal>] AssemblyFileVersion = "6.0.6"
    let [<Literal>] AssemblyInformationalVersion = "6.0.6"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "c142d04ac0b623f677933761209aacc8a16d337e"
