// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("EFCore.FSharp.Tests")>]
[<assembly: AssemblyProductAttribute("EFCore.FSharp")>]
[<assembly: AssemblyVersionAttribute("6.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-11-09T00:00:00.0000000+00:00")>]
[<assembly: AssemblyFileVersionAttribute("6.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("6.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","08012ceb9901dbc29a12b7745c94f406db8b1fc3")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "EFCore.FSharp.Tests"
    let [<Literal>] AssemblyProduct = "EFCore.FSharp"
    let [<Literal>] AssemblyVersion = "6.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-11-09T00:00:00.0000000+00:00"
    let [<Literal>] AssemblyFileVersion = "6.0.0"
    let [<Literal>] AssemblyInformationalVersion = "6.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "08012ceb9901dbc29a12b7745c94f406db8b1fc3"
